CREATE TABLE Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    Role INTEGER NOT NULL,
    FullName TEXT NOT NULL,
    IsActive INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE Vehicles (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    LicensePlate TEXT NOT NULL UNIQUE,
    Type INTEGER NOT NULL
);

CREATE TABLE ParkingTickets (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    VehicleId INTEGER NOT NULL,
    EntryTime TEXT NOT NULL,
    ExitTime TEXT NULL,
    IsPaid INTEGER NOT NULL DEFAULT 0,
    CreatedByUserId INTEGER NOT NULL,
    FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id),
    FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id)
);

CREATE TABLE Payments (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TicketId INTEGER NOT NULL UNIQUE,
    PaidAt TEXT NOT NULL,
    Amount REAL NOT NULL,
    Method TEXT NOT NULL,
    FOREIGN KEY (TicketId) REFERENCES ParkingTickets(Id)
);
